include:
  - board: seeeduino_xiao
    shield: tbkmini_left
  - board: seeeduino_xiao
    shield: tbkmini_right
  - board: seeeduino_xiao
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
